apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-healthcheck
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts: [healthcheck.example.com]
      secretName: healthcheck-tls
  rules:
    - host: healthcheck.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cluster-healthcheck
                port:
                  name: http