apiVersion: v1
kind: Service
metadata:
  name: cluster-healthcheck
  namespace: cluster-healthcheck
spec:
  selector:
    app: cluster-healthcheck
  ports:
    - name: http
      port: 80
      targetPort: 8080